import * as React from "react";
import type { Metadata } from "next";

import LocalFont from "next/font/local";

import "./globals.css";
import { Box } from "@mui/material";
const pingFang = LocalFont({
  src: "./fonts/PingFang Regular.ttf",
  variable: "--pingfang-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="zh">
      <body className={pingFang.variable}>
        <Box
          sx={{
            backgroundColor: 'grey.100',  // 背景颜色
            minHeight: '100vh',          // 确保背景颜色充满整个屏幕高度
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          {children}
        </Box>
      </body>
    </html>
  );
}
